# Generated by Django 3.2.25 on 2024-04-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegame',
            name='is_image_used',
            field=models.BooleanField(default=False),
        ),
    ]
