# Generated by Django 3.2.25 on 2024-04-11 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_imagegame_used_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedImageByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts_history', models.TextField(default='')),
                ('attempt_no', models.IntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagegame',
            name='used_for_today',
        ),
        migrations.DeleteModel(
            name='UsedImage',
        ),
        migrations.AddField(
            model_name='usedimagebyuser',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.imagegame', unique=True),
        ),
        migrations.AddField(
            model_name='usedimagebyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
