# Generated by Django 3.2.25 on 2024-04-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20240411_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedimagebyuser',
            name='attempt_no',
            field=models.IntegerField(default=0),
        ),
    ]
