# Generated by Django 3.2.25 on 2024-04-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_usedimagebyuser_attempt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegame',
            name='used_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
