# Generated by Django 3.2.25 on 2024-04-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_imagegame_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedimagebyuser',
            name='pixelation_level',
            field=models.IntegerField(default=0),
        ),
    ]
