# Generated by Django 3.2.25 on 2024-04-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_usedimagebyuser_pixelation_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedimagebyuser',
            name='is_attempt_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usedimagebyuser',
            name='is_user_win',
            field=models.BooleanField(default=False),
        ),
    ]
