# Generated by Django 3.2.25 on 2024-04-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20240411_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedimagebyuser',
            old_name='is_attempt_left',
            new_name='is_attempt_done',
        ),
    ]
